auth: 公用代码放在application里
message: 开发环境application

spring:
  cloud.config:
    allowOverride: true #外部源配置是否可被覆盖,相当于它会覆盖本地的同名配置项
    overrideNone: false #外部源配置是否不覆盖任何源
    overrideSystemProperties: false #仅仅系统属性和环境变量
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
---
spring:
  profiles: dev-common
  common:
    dic: 字典
    message: 消息配置
---
spring:
  profiles: dev-mongo
  data.mongodb:
    uri: mongodb://localhost:27073/test
---
spring:
  profiles: dev-redis
  redis:
    host: localhost
    port: 6379
---
spring:
  profiles: dev-rabbitmq
  rabbitmq:
    addresses: localhost:5672
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    virtual-host: ${RABBIT_VHOST:/}
    publisherConfirms: true
    stomp-port: 61613